export const environment = {
  firebase: {
    projectId: '',
    appId: '',
    storageBucket: '',
    apiKey: '',
    authDomain: '',
    messagingSenderId: '',
    measurementId: '',
  },
  production: true,
  apiUrl: '',
  apiUrlOrganization: '',
  apiUrlActivities: '',
  apiUrlCategories: '',
  apiUrlmembers: '',
  apiUrlusers: '',
  apiUrlNews: '',
  apiUrlNewsList: '',
  apiUrlNewsListById: '',
  apiUrlNewsPost: '',
  apiUrlNewsUpdate: '',
  apiUrlNewsDelete: '',
  apiUrlMembers: '',
  apiUrlLogin: '',
  apiUrlRegister: '',
  apiUrlUsers: '',
  apiUrlSlides: '',
  apiUrlContacts: '',
  wikimediaMap: '',
};
