export const environment = {
  production: true,
  apiUrl: '',
  apiUrlOrganization: '',
  apiUrlActivities: '',
  apiUrlCategories: '',
  membersApiUrl: '',
  users: '',
  apiUrlNews: "",
  apiUrlNewsList: "",
  apiUrlNewsListById: "",
  apiUrlNewsPost: "",
  apiUrlNewsUpdate: "",
  apiUrlNewsDelete: "",
};
