export const environment = {
  production: true,
  apiUrl: '',
  apiUrlOrganization: '',
  apiUrlActivities: '',
  apiUrlCategories: '',
  apiUrlmembers: '', 
  apiUrlusers: '',
  apiUrlNews: "",
  apiUrlNewsList: "",
  apiUrlNewsListById: "",
  apiUrlNewsPost: "",
  apiUrlNewsUpdate: "",
  apiUrlNewsDelete: "",
  apiUrlMembers: "",
  apiUrlLogin: "",
  apiUrlRegister: "",
  apiUrlUsers: "",
  apiUrlSlides: ""
};
